services:
  - type: web
    name: stockwise-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node cloud.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
